$ErrorActionPreference = 'Stop'
$path = 'admin-app.js'
$content = [System.IO.File]::ReadAllText((Resolve-Path $path), [System.Text.Encoding]::GetEncoding(1252))
function Rx([string]$pattern, [string]$replacement) { $script:content = [regex]::Replace($script:content, $pattern, $replacement) }

Rx 'dashboard: \[''.*?'', ''Dashboard'', ''/ Overview''\],' 'dashboard: [''\uD83C\uDFE0'', ''Dashboard'', ''/ Overview''],'
Rx 'users: \[''.*?'', ''User Management'', ''/ Accounts & Roles''\],' 'users: [''\uD83D\uDC65'', ''User Management'', ''/ Accounts & Roles''],'
Rx 'inventory: \[''.*?'', ''Library Inventory'', ''/ Books & Resources''\],' 'inventory: [''\uD83D\uDCDA'', ''Library Inventory'', ''/ Books & Resources''],'
Rx 'transactions: \[''.*?'', ''Transactions'', ''/ Loans & Returns''\],' 'transactions: [''\uD83D\uDD04'', ''Transactions'', ''/ Loans & Returns''],'
Rx 'reports: \[''.*?'', ''Reports & Analytics'', ''/ Insights''\],' 'reports: [''\uD83D\uDCCA'', ''Reports & Analytics'', ''/ Insights''],'
Rx 'system: \[''.*?'', ''System Maintenance'', ''/ Backup & Settings''\],' 'system: [''\u2699'', ''System Maintenance'', ''/ Backup & Settings''],'
Rx 'audit: \[''.*?'', ''Audit Log'', ''/ Activity History''\],' 'audit: [''\uD83E\uDDFE'', ''Audit Log'', ''/ Activity History''],'
Rx 'const \[icon, title, breadcrumb\] = titles\[section\] \|\| \[''.*?'', section, ''/''\];' 'const [icon, title, breadcrumb] = titles[section] || [''\uD83D\uDCCC'', section, ''/''];'
Rx 'document\.getElementById\(''confirmIcon''\)\.textContent = icon \|\| ''.*?'';' 'document.getElementById(''confirmIcon'').textContent = icon || ''\u26A0'';'
Rx 'function showToast\(type, msg, icon = ''.*?''\) \{' 'function showToast(type, msg, icon = ''\u2139'') {'
Rx '<button class="toast-close" onclick="this\.parentElement\.remove\(\)">.*?</button>' '<button class="toast-close" onclick="this.parentElement.remove()">\u00D7</button>'
Rx '<div class="es-icon">.*?</div><p>No admin activity yet\.</p>' '<div class="es-icon">\uD83D\uDCED</div><p>No admin activity yet.</p>'
Rx '<div class="es-icon">.*?</div><p>No users match your filters\.</p>' '<div class="es-icon">\uD83D\uDC65</div><p>No users match your filters.</p>'
Rx '<button class="kebab-btn" onclick="toggleKebab\(event,''kb-\$\{user\.id\}''\)">.*?</button>' '<button class="kebab-btn" onclick="toggleKebab(event,''kb-${user.id}'')">\u22EE</button>'
Rx '<div class="kebab-item" onclick="editUser\(''\$\{user\.id\}''\)">.*? Edit Details</div>' '<div class="kebab-item" onclick="editUser(''${user.id}'')">\u270F Edit Details</div>'
Rx '<div class="kebab-item" onclick="toggleStatus\(''\$\{user\.id\}''\)">\$\{user\.status === ''Active'' \? ''.*? Deactivate'' : ''.*? Activate''\}</div>' '<div class="kebab-item" onclick="toggleStatus(''${user.id}'')">${user.status === ''Active'' ? ''\u23F8 Deactivate'' : ''\u2705 Activate''}</div>'
Rx '<div class="kebab-item danger" onclick="deleteUser\(''\$\{user\.id\}''\)">.*? Delete Account</div>' '<div class="kebab-item danger" onclick="deleteUser(''${user.id}'')">\uD83D\uDDD1 Delete Account</div>'
Rx 'showToast\(''error'', ''Please fill all required member fields\.'', ''.*?''\);' 'showToast(''error'', ''Please fill all required member fields.'', ''\u26A0'');'
Rx 'showToast\(''error'', ''Please set a password for the new member\.'', ''.*?''\);' 'showToast(''error'', ''Please set a password for the new member.'', ''\uD83D\uDD12'');'
Rx 'showToast\(''error'', ''Passwords do not match\.'', ''.*?''\);' 'showToast(''error'', ''Passwords do not match.'', ''\uD83D\uDD10'');'
Rx 'showToast\(''success'', ''Member account created successfully\.'', ''.*?''\);' 'showToast(''success'', ''Member account created successfully.'', ''\uD83D\uDC64'');'
Rx 'showToast\(''error'', error\.message \|\| ''Unable to save member\.'', ''.*?''\);' 'showToast(''error'', error.message || ''Unable to save member.'', ''\u26A0'');'
Rx 'showToast\(''success'', `Account marked \$\{nextStatus\}\.`, ''.*?''\);' 'showToast(''success'', `Account marked ${nextStatus}.`, ''\uD83D\uDD04'');'
Rx 'showToast\(''error'', error\.message \|\| ''Unable to update status\.'', ''.*?''\);' 'showToast(''error'', error.message || ''Unable to update status.'', ''\u26A0'');'
Rx 'confirmAction\(''Delete Account'', `Delete <strong>\$\{LibraryApp\.escapeHtml\(user\.user_name\)\}</strong>\? This will remove the member\\''s login access\.`, ''.*?'', async \(\) => \{' 'confirmAction(''Delete Account'', `Delete <strong>${LibraryApp.escapeHtml(user.user_name)}</strong>? This will remove the member\''s login access.`, ''\uD83D\uDDD1'', async () => {'
Rx 'showToast\(''success'', ''Member deleted successfully\.'', ''.*?''\);' 'showToast(''success'', ''Member deleted successfully.'', ''\uD83D\uDDD1'');'
Rx 'showToast\(''error'', error\.message \|\| ''Unable to delete member\.'', ''.*?''\);' 'showToast(''error'', error.message || ''Unable to delete member.'', ''\u26A0'');'
Rx '<div class="es-icon">.*?</div><p>No books found in the shared catalog yet\.</p>' '<div class="es-icon">\uD83D\uDCDA</div><p>No books found in the shared catalog yet.</p>'
Rx 'font-size:1\.2rem">.*?</div>' 'font-size:1.2rem">\uD83D\uDCD8</div>'
Rx 'onclick="event\.stopPropagation\(\);viewBook\(''\$\{book\.id\}''\)">.*?</button>' 'onclick="event.stopPropagation();viewBook(''${book.id}'')">\uD83D\uDC41</button>'
Rx 'onclick="saveBook\(\)">.*? Save Book</button>' 'onclick="saveBook()">\uD83D\uDCBE Save Book</button>'
Rx 'showToast\(''success'', ''Book added to the shared catalog\.'', ''.*?''\);' 'showToast(''success'', ''Book added to the shared catalog.'', ''\uD83D\uDCDA'');'
Rx 'showToast\(''error'', error\.message \|\| ''Unable to add book\.'', ''.*?''\);' 'showToast(''error'', error.message || ''Unable to add book.'', ''\u26A0'');'
Rx 'font-size:2\.5rem;flex-shrink:0">.*?</div>' 'font-size:2.5rem;flex-shrink:0">\uD83D\uDCD6</div>'
Rx '<div class="es-icon">.*?</div><p>No transactions available yet\.</p>' '<div class="es-icon">\uD83D\uDD04</div><p>No transactions available yet.</p>'
Rx 'title: ''.*? User Distribution''' 'title: ''\uD83D\uDC65 User Distribution'''
Rx 'title: ''.*? Most Borrowed Books''' 'title: ''\uD83C\uDFC6 Most Borrowed Books'''
Rx 'title: ''.*? Inventory by Category''' 'title: ''\uD83D\uDCDA Inventory by Category'''
Rx 'title: ''.*? Fine Summary''' 'title: ''\u2696 Fine Summary'''
Rx '`.*?\$\{finesTotal\}`' '`\u20B9${finesTotal}`'
Rx 'showToast\(''success'', `Live \$\{format\.toUpperCase\(\)\} export can be added next\.`, ''.*?''\);' 'showToast(''success'', `Live ${format.toUpperCase()} export can be added next.`, ''\uD83D\uDCE4'');'
Rx '<div class="es-icon">.*?</div><p>No audit entries match your filters\.</p>' '<div class="es-icon">\uD83E\uDDFE</div><p>No audit entries match your filters.</p>'
Rx 'showToast\(''success'', ''Backup completed successfully\.'', ''.*?''\);' 'showToast(''success'', ''Backup completed successfully.'', ''\uD83D\uDCBE'');'
Rx 'showToast\(''error'', error\.message \|\| ''Backup failed\.'', ''.*?''\);' 'showToast(''error'', error.message || ''Backup failed.'', ''\u26A0'');'
Rx 'function confirmRestore\(\) \{ showToast\(''info'', ''Restore flow is disabled to protect the shared JSON database\.'', ''.*?''\); \}' 'function confirmRestore() { showToast(''info'', ''Restore flow is disabled to protect the shared JSON database.'', ''\uD83D\uDEE1''); }'
Rx 'function scheduleChanged\(name, toggle\) \{ showToast\(toggle\.checked \? ''success'' : ''info'', `\$\{name\} schedule \$\{toggle\.checked \? ''enabled'' : ''disabled''\}\.`, ''.*?''\); \}' 'function scheduleChanged(name, toggle) { showToast(toggle.checked ? ''success'' : ''info'', `${name} schedule ${toggle.checked ? ''enabled'' : ''disabled''}.`, ''\u23F0''); }'
Rx 'map\(\(user\) => `.*? \$\{user\.user_name\}`\)' 'map((user) => `\uD83D\uDC64 ${user.user_name}`)'
Rx 'map\(\(book\) => `.*? \$\{book\.title\}`\)' 'map((book) => `\uD83D\uDCDA ${book.title}`)'
Rx 'if \(matches\.length\) showToast\(''info'', matches\.join\(''.*?''\), ''.*?''\);' 'if (matches.length) showToast(''info'', matches.join('' \u2022 ''), ''\uD83D\uDD0E'');'
Rx 'showToast\(''error'', error\.message \|\| ''Unable to load admin dashboard\.'', ''.*?''\);' 'showToast(''error'', error.message || ''Unable to load admin dashboard.'', ''\u26A0'');'

[System.IO.File]::WriteAllText((Resolve-Path $path), $content, [System.Text.UTF8Encoding]::new($false))
